logging:
  level:
    org.chika.memoria: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://cluster0.dgqgb.mongodb.net/memoria
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: clientId
            clientSecret: clientSecret
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

springdoc:
  api-docs:
    path: ${API_DOCS_URL:/api-docs}
    enabled: ${API_DOCS_ENABLED:true}
    resolve-schema-properties: true
  swagger-ui:
    csrf:
      enabled: true
    disable-swagger-default-url: true
    url: ${API_DOCS_URL:/api-docs}
    path: ${API_DOCS_URL:/api-docs}/swagger
    use-root-path: true

memoria:
  microsoft:
    clientId: clientId
    clientSecret: clientSecret
    redirectUri: http://localhost:3000/login/microsoft

application:
  corsOrigins:
    - http://localhost:3000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000
  security:
    tokenExpiration: 864000000    # milliseconds
    privateJwtKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKAIBAAKCAgEAj35iSAeUSbr/XFIhzcCRej1Oth8h3Ky0gVjCBhlfbyOgjL3z
      o29MXvltyaE3/jJAvz1l5XPXGFWR798dQxDAAGUPce+GXaRcfkM9MMFRTzOczljK
      UEc0zQn9z1Xgjq2rWVJPiKlgyqOF5heOEIaeXImShw52hqLx/NBnfunTviZuESYe
      Hq6piFjOj69qMODPeccEc8Rnl12v/3ca5Y3ULqYLeve3vhLij21nwYZ/1xQYd7Ed
      kimnsWgG1ByzcxJ4jEREbYc0Y+5igDLSou0oU7BaxLcb03m4l8psPjjdlt4OLMcI
      GQLwW6LXJOE+mtHHH8ZN0jGZGG55ye6Xpmf0QkHbxfy5GOOpyUeLCpnRu0PHjv4L
      B/k6WZjX6kSrqHQYK680b4nTffDHCX0glIKyVfjQghRE+0j1RvfohTlzTK8xJs90
      gvj4Lrz7Xemc+LaIGkx7Jy+6wVy72lIUFfptrpCtHTmNQQ3wbHLCyq9OE7RoWj1v
      bNLVwhvzg88s0iBnduzOFnU26J21X38Jwy0NzivlpbMS+gDlPHpya0cZC13O0SXO
      FUxWFcAo6GPoM7b0k+TWt6X3LxMjaFc0xxuJXxIrEaAOqgyu2FybCCwOUAp+mpL2
      w5eiWWqxZOGWLXRiiO9gUCTim1OJqLE80lJx1/df5kvG3cPg0pMBWgmZb9sCAwEA
      AQKCAgAudYoWrjWJ5by2RHVja7zuahkpCE1raJOM6ZLwbJikoFFkIEBZIzkD6xhr
      1wINEHI8OQHb17TF0TbOBlwwEaVIu2/TwOytNwEndFfEiGLuFNTpToA6m8Nxu5Fs
      5u4s4/f9lJPhuI15Lpa0192MZjmx1m0Vw04G640UANnxkn2XLFQow0GvR3fmiHJg
      vTfRmYgzcodzgBzWOmQ4f3S67D/N1r8S0k+wf+bQ72hPlV+g4IXHgxYC8++yle7Y
      EG7djBZxu8y39bW1wUItJcdjLwwGhKvu0yZ0Qw3MP6LqRnkgVscaIlrx1izCTqf/
      7dnaQJ+LHyalLp/V9DcEdXauTywbIxrGhJKgJ4xpTjVabKhMhHlrKcNPHCLwzlrE
      AY4J84bBj2vSMY24Ycs//1Vqti8hSRk6mm3MCYurnHdNdjauUzqjLxVxPK5CLtMn
      R5NMt5ZwjbTVjHOf6pwZqiE412/KjgdNkR+XDPvZg7EasEQCm23ZdI7wKKBXn8mx
      qpaxq53g+9aP5BnS6NmqccoIYkVjrQi1A1gvQQINlk4PKce+WP2ikyA/EU3piGh8
      9D3PpsH9iRdFa+8SabkQufjF+t29va9+ymkSkuYZlnNS9zJI5vEs06/QSOlgeNhU
      KD9d0nhZdjF2mejX4FE+arB1WzP/AHDFvDkn6r0HdsZejZijyQKCAQEA+t/h/SR9
      657umf8HsbwkF78gM0FJPLTC6fEVih1fDda7EtBV7SrEkOjb42frXFtn62wbOK4p
      4osqHEutZYQHY2X3z5Zyc9q0I39OxVBZN6RzT+lxwcI5E+ooDgbrTClk7aLi7Q4U
      vjQx7kd+N5XGQUlUaaEjNscVYVG9pnNaGS/HeaMQPZxU5pR3yOfx45UDoyz18Yd7
      oJBW2rA5oifjFHWJRauclBnTynD6QDBOW5w4dxk7KW9jR8dggVInd0Cr591pp3of
      k83b5sb0CsSQ8lauqS86W2i7Jrkm42ZkYWIy5ECjgLfwoEBqOXiXceVvX/FlWCIb
      LUSoGcEAkoWOFQKCAQEAkmzhdeiv72jKma44FmRPcDLz+MLC225N9DG2Qvhp1aDG
      Fj1OBCzFyGaJEVNK/WsMTsbEv8NhEu47HUgaDn6qK3X6XV+AnHp5lcnsVqmKoAqC
      x18VEyJIoOQUX3OewklUrZ9T4gAImu98PT6Sm2xCsd0s3RpYuEVAkVraPkqwIx3P
      vQJeoY8gpYTt/dzgwyWLrySLRZouYqHcwJEPnKFuvDqIfyk8zMggDeVTPqAX+Se7
      p8kcRLBzJU7NZNJAn/TFUUHc+/jYv39K8kCYYGUxP1dNX4jrvASdEYSHrUlsCJZi
      lYrfESpeJexNFDXg5yrviqI/NiIcN8tliFJ3dVNyLwKCAQEAgM7MqH3BDWZH2deg
      qrgPzAV80fQ2Vy30WctHpOdZs7BJ0uoXBDOOQ1zb8ZGcvYnM/IpAG8UIimGrmGWe
      vN2iMX3cU8BKOYPUM9mcpyCO/ku4TRJuLu67AaebM0CINU2XnY+hdddh/RqtfEtG
      2eFTrpeo+KccfnaPWq1uc3UMkJwAjkqT/x4yVUVrj0LP5mrPOEvQZ1eJuTIC9ju/
      C6vxIsMKXTQ0q7HrFSkWxDhJMy4tq7DPuIGRdvw+Z4e37bnNybncEnpYljn/KymB
      ibnNNjAdc45lJyPJ26L6/YzIA1w5BwrNKDzJFm6cW6+4Cmmj2p4Fy8+PJpn2uWpo
      EdLy1QKCAQAhH2ItEvLhfFoAQ6nKXuydW9lWl3AOxTf7Gle5dIo0WgcVNs70INCo
      0ZEGC0p2YwXIuCv/mQnXh2515D6Istx5slltT9I/E3F3kdLVk8qZA2esA/U3e9Tk
      GFQHd5cdKgturxEBmbJYof3/uKzfXbEEnRyt82zIWloNx3iBCNIpT3ATuHqBn2fq
      KVTQzWtGmbKsbt7WYtdFVooiQW4/p0DucWs5ILHxPQALRKn9C6gAo51Oii7L1wJl
      GRtbSDh4Np2AER8VHKijQP9KJ5SQkbN/OZd2GfoBcSW6tbkfWPGIS8SHQX/OWUAs
      4fRZswpqIItJWARmkXbCpE8WdFkzgCnfAoIBAHAnU4stv0Y1TmWz1t3GswVBmZJ3
      adEAjDezSupU0TPOlMXmV9FjZRsxr8ixXqbZmCKrtpIEuPwtohq34UJGlXwvbL5Y
      ToKwg60n2dsOZLWFKlJeDOX78XMZXid6ZveYWvN7YgX6sMEZ4PhXdL/fSngtbRsh
      /PFhgMTwUadGZbzcpY3QLRxndIegQ5WLyQF+pbp7x29/GvubkJX8ifiBgPKS6vUN
      2uibl9VqlHznhbZemflgcqtJSGjIGpbBNecOTY2fi8csFw1XYu48+PA7HdsSFQ5p
      93yJ60VgLuXwXt3rBtzidF8TXuhCu0JFzQqOc4ebojNvxVimDve9aRtIaMA=
      -----END RSA PRIVATE KEY-----
    publicJwtKey: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAj35iSAeUSbr/XFIhzcCR
      ej1Oth8h3Ky0gVjCBhlfbyOgjL3zo29MXvltyaE3/jJAvz1l5XPXGFWR798dQxDA
      AGUPce+GXaRcfkM9MMFRTzOczljKUEc0zQn9z1Xgjq2rWVJPiKlgyqOF5heOEIae
      XImShw52hqLx/NBnfunTviZuESYeHq6piFjOj69qMODPeccEc8Rnl12v/3ca5Y3U
      LqYLeve3vhLij21nwYZ/1xQYd7EdkimnsWgG1ByzcxJ4jEREbYc0Y+5igDLSou0o
      U7BaxLcb03m4l8psPjjdlt4OLMcIGQLwW6LXJOE+mtHHH8ZN0jGZGG55ye6Xpmf0
      QkHbxfy5GOOpyUeLCpnRu0PHjv4LB/k6WZjX6kSrqHQYK680b4nTffDHCX0glIKy
      VfjQghRE+0j1RvfohTlzTK8xJs90gvj4Lrz7Xemc+LaIGkx7Jy+6wVy72lIUFfpt
      rpCtHTmNQQ3wbHLCyq9OE7RoWj1vbNLVwhvzg88s0iBnduzOFnU26J21X38Jwy0N
      zivlpbMS+gDlPHpya0cZC13O0SXOFUxWFcAo6GPoM7b0k+TWt6X3LxMjaFc0xxuJ
      XxIrEaAOqgyu2FybCCwOUAp+mpL2w5eiWWqxZOGWLXRiiO9gUCTim1OJqLE80lJx
      1/df5kvG3cPg0pMBWgmZb9sCAwEAAQ==
      -----END PUBLIC KEY-----