logging:
  level:
    org.chika.memoria: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://chika:41PLGL6MMyhxmMvUjy17@cluster0.dgqgb.mongodb.net/memoria
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: clientId
            clientSecret: clientSecret
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

springdoc:
  api-docs:
    path: ${API_DOCS_URL:/api-docs}
    enabled: ${API_DOCS_ENABLED:true}
    resolve-schema-properties: true
  swagger-ui:
    csrf:
      enabled: true
    disable-swagger-default-url: true
    url: ${API_DOCS_URL:/api-docs}
    path: ${API_DOCS_URL:/api-docs}/swagger
    use-root-path: true

memoria:
  microsoft:
    clientId: clientId
    clientSecret: clientSecret
    redirectUri: http://localhost:3000/login/microsoft

application:
  corsOrigins:
    - http://localhost:3000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000
  security:
    tokenExpiration: 864000000    # milliseconds
    privateJwtKey: private-key
    publicJwtKey: public-key